#!/bin/bash
systemctl stop log-pend00
systemctl disable log-pend00
systemctl stop log-pend01
systemctl disable log-pend01
systemctl stop log-pend02
systemctl disable log-pend02
systemctl stop log-pend03
systemctl disable log-pend03
systemctl stop log-pend04
systemctl disable log-pend04
systemctl stop log-pend05
systemctl disable log-pend05
systemctl stop log-pend06
systemctl disable log-pend06
systemctl stop log-pend07
systemctl disable log-pend07
systemctl stop log-pend08
systemctl disable log-pend08
systemctl stop log-pend09
systemctl disable log-pend09
systemctl stop log-pend10
systemctl disable log-pend10
systemctl stop log-pend11
systemctl disable log-pend11
systemctl stop log-pend12
systemctl disable log-pend12
systemctl stop log-pend13
systemctl disable log-pend13
systemctl stop log-pend14
systemctl disable log-pend14
systemctl stop log-pend15
systemctl disable log-pend15
systemctl stop log-pend16
systemctl disable log-pend16
systemctl stop log-pend17
systemctl disable log-pend17
systemctl stop log-pend18
systemctl disable log-pend18
systemctl stop log-pend19
systemctl disable log-pend19
systemctl stop log-pend20
systemctl disable log-pend20
systemctl stop log-pend21
systemctl disable log-pend21
systemctl stop log-pend22
systemctl disable log-pend22
systemctl stop log-pend23
systemctl disable log-pend23
systemctl stop log-pend24
systemctl disable log-pend24
systemctl stop log-pend25
systemctl disable log-pend25
systemctl stop log-pend26
systemctl disable log-pend26
systemctl stop log-pend27
systemctl disable log-pend27
systemctl stop log-pend28
systemctl disable log-pend28
systemctl stop log-pend29
systemctl disable log-pend29
systemctl stop log-pend30
systemctl disable log-pend30
systemctl stop log-pend31
systemctl disable log-pend31
systemctl stop log-pend32
systemctl disable log-pend32
systemctl stop log-pend33
systemctl disable log-pend33
systemctl stop log-pend34
systemctl disable log-pend34
systemctl stop log-pend35
systemctl disable log-pend35
systemctl stop log-pend36
systemctl disable log-pend36
systemctl stop log-pend37
systemctl disable log-pend37
systemctl stop log-spin30
systemctl disable log-spin30
systemctl stop log-spin31
systemctl disable log-spin31
systemctl stop log-spin32
systemctl disable log-spin32
systemctl stop log-spin33
systemctl disable log-spin33
systemctl stop log-spin34
systemctl disable log-spin34
systemctl stop log-spin35
systemctl disable log-spin35
systemctl stop log-spin36
systemctl disable log-spin36
systemctl stop log-spin37
systemctl disable log-spin37
systemctl stop log-spin38
systemctl disable log-spin38
systemctl stop log-spin39
systemctl disable log-spin39
systemctl stop log-spin40
systemctl disable log-spin40
systemctl stop log-spin41
systemctl disable log-spin41
systemctl stop log-spin42
systemctl disable log-spin42
systemctl stop log-spin43
systemctl disable log-spin43
systemctl stop log-spin44
systemctl disable log-spin44
systemctl stop log-spin45
systemctl disable log-spin45
systemctl stop log-spin46
systemctl disable log-spin46
systemctl stop log-spin47
systemctl disable log-spin47
systemctl stop log-spin48
systemctl disable log-spin48
systemctl stop log-spin49
systemctl disable log-spin49
systemctl stop log-spin50
systemctl disable log-spin50
systemctl stop log-spin51
systemctl disable log-spin51
systemctl stop log-spin52
systemctl disable log-spin52
systemctl stop log-spin53
systemctl disable log-spin53
systemctl stop log-spin54
systemctl disable log-spin54
systemctl stop log-spin55
systemctl disable log-spin55
systemctl stop log-spin56
systemctl disable log-spin56
systemctl stop log-spin57
systemctl disable log-spin57
systemctl stop log-spin58
systemctl disable log-spin58
systemctl stop log-spin59
systemctl disable log-spin59
systemctl stop log-spin60
systemctl disable log-spin60
systemctl stop log-spin61
systemctl disable log-spin61
systemctl stop log-spin62
systemctl disable log-spin62
systemctl stop log-spin63
systemctl disable log-spin63
systemctl stop log-spin64
systemctl disable log-spin64
systemctl stop log-spin65
systemctl disable log-spin65
systemctl stop log-spin66
systemctl disable log-spin66
systemctl stop log-spin67
systemctl disable log-spin67
systemctl stop log-spin68
systemctl disable log-spin68
systemctl stop log-spin69
systemctl disable log-spin69
systemctl stop log-spin70
systemctl disable log-spin70
systemctl stop log-spin71
systemctl disable log-spin71
systemctl stop log-spin72
systemctl disable log-spin72
systemctl stop log-spin73
systemctl disable log-spin73
systemctl stop log-spin74
systemctl disable log-spin74
systemctl stop log-spin75
systemctl disable log-spin75
systemctl stop log-spin76
systemctl disable log-spin76
systemctl stop log-spin77
systemctl disable log-spin77
