#!/bin/bash
systemctl enable log-spin40
systemctl start log-spin40
systemctl enable log-spin41
systemctl start log-spin41
systemctl enable log-spin42
systemctl start log-spin42
systemctl enable log-spin43
systemctl start log-spin43
systemctl enable log-spin44
systemctl start log-spin44
systemctl enable log-spin45
systemctl start log-spin45
systemctl enable log-spin46
systemctl start log-spin46
systemctl enable log-spin47
systemctl start log-spin47
systemctl enable log-spin48
systemctl start log-spin48
systemctl enable log-spin49
systemctl start log-spin49
