#!/bin/bash
systemctl enable log-spin60
systemctl start log-spin60
systemctl enable log-spin61
systemctl start log-spin61
systemctl enable log-spin62
systemctl start log-spin62
systemctl enable log-spin63
systemctl start log-spin63
systemctl enable log-spin64
systemctl start log-spin64
systemctl enable log-spin65
systemctl start log-spin65
systemctl enable log-spin66
systemctl start log-spin66
systemctl enable log-spin67
systemctl start log-spin67
systemctl enable log-spin68
systemctl start log-spin68
systemctl enable log-spin69
systemctl start log-spin69
