#!/bin/bash
systemctl enable log-spin50
systemctl start log-spin50
systemctl enable log-spin51
systemctl start log-spin51
systemctl enable log-spin52
systemctl start log-spin52
systemctl enable log-spin53
systemctl start log-spin53
systemctl enable log-spin54
systemctl start log-spin54
systemctl enable log-spin55
systemctl start log-spin55
systemctl enable log-spin56
systemctl start log-spin56
systemctl enable log-spin57
systemctl start log-spin57
systemctl enable log-spin58
systemctl start log-spin58
systemctl enable log-spin59
systemctl start log-spin59
